### ISSUE TITLE
This demo does NOT WORK

### ISSUE THREAD

**Issue by advancedsoftwarecanada** [muaz-khan/MultiRTC#4]
Connection issues galore. Cannot get this demo to work on your server.

**Comment by muaz-khan** [comment]
You can try this demo:

* https://github.com/muaz-khan/MultiRTC/tree/master/MultiRTC-socketio

Or this:

* https://github.com/muaz-khan/MultiRTC/tree/master/MultiRTC-websocket

and both should work.

PS. Following demo is fixed as well:

* https://www.webrtc-experiment.com/RTCMultiConnection/MultiRTC/
